apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api
  labels:
    app: udagram-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user-api
  template:
    metadata:
      labels:
        app: udagram-user-api
    spec:
      containers:
      - name: udagram-api-user-service
        image: dealio/udagram-api-user-service
        ports:
        - containerPort: 8080
